### ISSUE TITLE
Feature useExpiredDataWhenNoLoaderAvailable() not working

### ISSUE THREAD

**Issue by arkantos1482** [VictorAlbertos/ReactiveCache#12]
It doesn't make any change in the behavior of the ReactiveCache, whether you add `useExpiredDataWhenNoLoaderAvailabe()` or not. 
Whenever data expires, the record will be removed from both memory and disk. (regardless of using `useExpiredDataWhenNoLoaderAvailabe()`)

The code:
customerProvider = new ReactiveCache.Builder() .useExpiredDataWhenNoLoaderAvailable() .diskCacheSize(5) .using(context.getCacheDir(), new GsonSpeaker()) .<Customer>provider() .lifeCache(15, TimeUnit.SECONDS) .withKey("CUSTOMER");

getCustomerApi.compose(customerProvider.readWithLoader());

**Comment by armin-abbasi** [comment]
Same issue here! Thanks for bringing it up!

**Comment by VictorAlbertos** [comment]
[Here take a look](https://github.com/VictorAlbertos/ReactiveCache/blob/2.x/reactive_cache/src/test/java/io/reactivecache2/ProviderTest.java#L47) I've just added two tests showing the `useExpiredDataWhenNoLoaderAvailabe` behaviour.   

Next time please submit a test to expose what is the problem. Otherwise, I will close the issue right away. If you don't make the effort to narrow the "problem", I won't do it for you.
