### ISSUE TITLE
Correct reactive base types

### ISSUE THREAD

**Issue by PaulWoitaschek** [VictorAlbertos/ReactiveCache#5]
Kind of the next steps of: https://github.com/VictorAlbertos/RxCache/issues/60

Many operations are returning the wrong observable type. The api would be way more meaningful if the correct types are returned. I.e

| method | current | expected |
| --- | --- | --- |
| evict | observable | completable |
| read | observable | single |
| readNullable | observable | single |

**Comment by VictorAlbertos** [comment]
Thanks for the suggestion. I'll start working on it after RxJava2 releases a final version.

Nevertheless, I'll need to think carefully about `replace()` and `readWithLoader()`, because I think the should return different reactive types based on the loader reactive type. We should provide support for `Observable`, `Single`, and `Flowable`, depending on the original type of the loader.

**Comment by VictorAlbertos** [comment]
I'm going to start with this implementation. @PaulWoitaschek, following your proposal, I will not provide a plethora of methods to support several reactive types, because, as you already said, the only right types (given the nature of this lib) as the one you listed before. 

| method | current | expected |
| --- | --- | --- |
| replace | observable | single |
| readWithLoader | observable | single |
| read | observable | single |
| evict | observable | completable |
| evictAll | observable | completable |
